CREATE TABLE IF NOT EXISTS students (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  age INTEGER NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  code INTEGER NOT NULL UNIQUE,
  grade VARCHAR(10) NOT NULL
)